import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core'
import { clients } from './clients'

export const projects = sqliteTable('projects', {
  id: text('id').primaryKey(),
  clientId: text('client_id').notNull().references(() => clients.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  description: text('description'),
  status: text('status').notNull().default('planning'), // planning, active, paused, completed, cancelled
  requirementsJson: text('requirements_json'), // Store technical requirements
  vaultReferencesJson: text('vault_references_json'), // Store vault assets mapping
  startDate: integer('start_date', { mode: 'timestamp_ms' }),
  deadline: integer('deadline', { mode: 'timestamp_ms' }),
  budgetAmount: real('budget_amount'),
  currencyCode: text('currency_code').notNull().default('INR'),
  currencySymbol: text('currency_symbol').notNull().default('₹'),
  currencyLocale: text('currency_locale').notNull().default('en-IN'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  deletedAt: integer('deleted_at', { mode: 'timestamp_ms' })
})

export const scopeChanges = sqliteTable('scope_changes', {
  id: text('id').primaryKey(),
  projectId: text('project_id').notNull().references(() => projects.id, { onDelete: 'cascade' }),
  description: text('description').notNull(),
  addedReqs: text('added_reqs'), // JSON array of added requirement IDs/descriptions
  removedReqs: text('removed_reqs'), // JSON array of removed requirement IDs/descriptions
  aiSummary: text('ai_summary'), // Impact summary generated by AI
  createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  deletedAt: integer('deleted_at', { mode: 'timestamp_ms' })
})
